site_name: Book Summarizer
site_description: A System for Books Processing and Summarization
site_url: https://www.go.to/web
site_author: Ricardo G. Sousa

nav:
  - Home: 'index.md'
  - Results: 'results.md'
  - About: 'about.md'

theme:
  name: readthedocs

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - pymdownx.superfences

plugins:
  - search
  - with-pdf:
      cover_subtitle: A brief report
      copyright: MIT
      output_path: 'pdf/booksum.pdf'
      author: Ricardo G. Sousa
      enabled_if_env: ENABLE_PDF_EXPORT