booksum_service:
  booksum:
    api_env: "prod"
    api_version: "0.1.0"
    api_description: "Book Summarizer - Index."
    api_title: "Book Sumarizer - Index."
    docs_url: "/docs"

    localhost:
      host: '0.0.0.0'
      port: '8001'

    local:
      host: 'ats-svc'
      port: '8001'

    remote:
      host: '0.0.0.0'
      port: '8001'

